// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include <fstream>
#include <sstream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 ", "[example]")
{
	string filename = "original.data";
	ifstream ifs;
	string buf;
	stringstream ss, tmp;
	int numbers[M][N];

	reform(filename);
	ifs.open("trans.data");
	for (int i = 0; i < M; i++)
	{
		for (int j = 0; j < N; j++)
		{
			ifs >> numbers[i][j];
			cout << numbers[i][j] << "\t";
		}
		cout << endl;
	}
	REQUIRE(numbers[0][0] == 5);
	REQUIRE(numbers[0][1] == 10);
	REQUIRE(numbers[0][2] == 60);
	REQUIRE(numbers[1][0] == 15);
	REQUIRE(numbers[1][1] == 20);
	REQUIRE(numbers[1][2] == 70);
	REQUIRE(numbers[2][0] == 25);
	REQUIRE(numbers[2][1] == 30);
	REQUIRE(numbers[2][2] == 80);
	REQUIRE(numbers[3][0] == 35);
	REQUIRE(numbers[3][1] == 40);
	REQUIRE(numbers[3][2] == 90);
	REQUIRE(numbers[4][0] == 45);
	REQUIRE(numbers[4][1] == 50);
	REQUIRE(numbers[4][2] == 100);
}
TEST_CASE("Ex2 ", "[example]")
{
	string filename = "test.data";
	ifstream ifs;
	string buf;
	stringstream ss, tmp;
	int numbers[M][N];

	reform(filename);
	ifs.open("trans.data");
	for (int i = 0; i < M; i++)
	{
		for (int j = 0; j < N; j++)
		{
			ifs >> numbers[i][j];
			cout << numbers[i][j] << "\t";
		}
		cout << endl;
	}
	REQUIRE(numbers[0][0] == 1);
	REQUIRE(numbers[0][1] == 4);
	REQUIRE(numbers[0][2] == 5);
	REQUIRE(numbers[1][0] == 2);
	REQUIRE(numbers[1][1] == 5);
	REQUIRE(numbers[1][2] == 6);
	REQUIRE(numbers[2][0] == 3);
	REQUIRE(numbers[2][1] == 6);
	REQUIRE(numbers[2][2] == 7);
	REQUIRE(numbers[3][0] == 4);
	REQUIRE(numbers[3][1] == 7);
	REQUIRE(numbers[3][2] == 8);
	REQUIRE(numbers[4][0] == 5);
	REQUIRE(numbers[4][1] == 8);
	REQUIRE(numbers[4][2] == 9);
}